### ISSUE TITLE
Figure out if we can auto-mark comments as Abuse

### ISSUE THREAD

**Issue by jonathanpeppers** [jonathanpeppers/inclusive-heat-sensor#11]
For example:

![image](https://github.com/user-attachments/assets/c33193ea-20cc-4168-9fe8-d47b9da0d123)

Then when I click it:

![image](https://github.com/user-attachments/assets/1f0f3e8c-a79c-4925-b5a0-6d87913733f9)

**Comment by haritha-mohan** [comment]
refs to bring up in sync: 
https://docs.github.com/en/communities/moderating-comments-and-conversations/managing-disruptive-comments
https://github.com/marketplace/actions/comment-hider
https://github.com/xamarin/xamarin-macios/blob/b7a317d06c24a4602053db2e3782efd6c3f8602e/tools/devops/automation/templates/build/build.yml#L193
https://github.com/int128/hide-comment-action
