### ISSUE TITLE
Accuracy testing / training

### ISSUE THREAD

**Issue by stewartsims** [jonathanpeppers/inclusive-heat-sensor#18]
As per my comment here: https://github.com/dotnet/maui/pull/25389

When deployed as a GitHub action in the dotnet MAUI repository this seems to have flagged up a lot of 'false positives'. 

Please can I request this and any future LLM based GH Actions get tested and / or trained on a representative corpus of data prior to being deployed?

Maybe a good way forward would be to decide on an acceptable success rate of any solution and present evidence that it meets this threshold before deploying it into a live situation where real contributors will receive notification their comment is deemed 'offensive or angry' (or find a way to remove the email notification of the result of the GitHub action).

**Comment by jonathanpeppers** [comment]
> I request this and any future LLM based GH Actions get tested and / or trained on a representative corpus of data prior to being deployed?

Yes, this was a test doing exactly this. How would you have prefer we have approached it differently?

**Comment by jonathanpeppers** [comment]
We have some experience doing this, such as:
* https://github.com/jonathanpeppers/inclusive-code-reviews-ml

We chose to use live comments, and our plan was that it would silently check, so we could review the data. But unfortunately, we found an issue:
* https://github.com/jonathanpeppers/inclusive-heat-sensor/issues/17

**Comment by stewartsims** [comment]
> We chose to use live comments, and our plan was that it would silently check, so we could review the data. But unfortunately, we found an issue:
> 
> * [Error from dotnet/maui repo #17](https://github.com/jonathanpeppers/inclusive-heat-sensor/issues/17)

I understand thanks for clarifying - it is good to know this was a bug and it was developed in good faith that it wouldn't impact people by sending an email notification.

> We have some experience doing this, such as:
> 
> * https://github.com/jonathanpeppers/inclusive-code-reviews-ml

Does this project I'm commenting on use the model / training mentioned above? Such research is exactly the kind of thing I had in mind, but if I understand correctly this project here uses a generic LLM or certainly it seems that way given it seems to struggle to correctly categorise the comments?

Since the email notification was an issue discovered during the testing via GitHub actions, which presumably should be resolved for any future testing, I'll leave this discussion at this point as obviously you should be free to experiment with tools like this if it is not impacting people directly.

**Comment by jonathanpeppers** [comment]
The model we made at https://github.com/jonathanpeppers/inclusive-code-reviews-ml is trained on real code review comments, but is easily outclassed by any LLM that is equivalent to gpt-4 or better. Our model's only benefit now, is that it is small, like 5-10MB depending on the format. Our model also can make mistakes just like LLMs, it sometimes considers a random string of letters as bad, but this is what we get with AI.

**Comment by jonathanpeppers** [comment]
Closing this, as we think the exit code problem is solved in:

* https://github.com/jonathanpeppers/inclusive-heat-sensor/releases/tag/v0.1.1

We are also tracking testing at:

* https://github.com/jonathanpeppers/inclusive-heat-sensor/issues/24
