### ISSUE TITLE
Enhancement: skip bot comments?

### ISSUE THREAD

**Issue by jonathanpeppers** [jonathanpeppers/inclusive-heat-sensor#23]
We could save some $$ by skipping comments posted by bots:
```
Comment: Title:  
Body:
<samp>
Azure Pipelines successfully started running 3 pipeline(s).<br>

</samp>
```

**Comment by rolfbjarne** [comment]
Looks like the github event says if it's a bot or not:

> "type": "Bot",

from:

https://productionresultssa1.blob.core.windows.net/actions-results/5842ea59-b8e7-4e69-93a1-c3ba6cef3490/workflow-job-run-de4be648-30a2-532e-74b6-c7b9be4471ae/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-11-01T14%3A20%3A27Z&sig=7DZs5nDgTEoIgPCmQipkShkGIRmTWbhkuCLkTyL4%2B8c%3D&ske=2024-11-02T02%3A00%3A51Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-11-01T14%3A00%3A51Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-08-04&sp=r&spr=https&sr=b&st=2024-11-01T14%3A10%3A22Z&sv=2024-08-04

for https://github.com/dotnet/maui/actions/runs/11630461303?pr=25550+%28comment%29
